"""
Abbott Chatbot - Demo with Mock Data (No API Key Required)

This demonstrates the complete flow using mock evaluator results.
"""

import pandas as pd


print("\n" + "🏥 ABBOTT MILK CHATBOT - DEMO ".center(80, "="))
print("\n📊 STEP 1: Dataset (10 samples)")
print("=" * 80)

# Original dataset
dataset = pd.DataFrame([
    {
        "customer_question": "Sữa Abbott nào tốt cho trẻ 1 tuổi?",
        "chatbot_answer": "Abbott Grow có thể phù hợp cho bé 1 tuổi."
    },
    {
        "customer_question": "Giá sữa Ensure Gold bao nhiêu?",
        "chatbot_answer": "Khoảng 800,000 VND/hộp 850g."
    },
    {
        "customer_question": "Sữa Similac có tốt cho trẻ sơ sinh không?",
        "chatbot_answer": "Có, Similac được thiết kế đặc biệt cho trẻ sơ sinh với hệ tiêu hóa non yếu."
    },
    {
        "customer_question": "Tôi muốn mua sữa cho bà ngoại 70 tuổi, nên chọn loại nào?",
        "chatbot_answer": "Ensure Gold là lựa chọn tốt cho người cao tuổi."
    },
    {
        "customer_question": "Sữa PediaSure có giúp trẻ tăng cân không?",
        "chatbot_answer": "PediaSure được thiết kế đặc biệt để hỗ trợ tăng trưởng chiều cao và cân nặng cho trẻ biếng ăn."
    },
    {
        "customer_question": "Có giao hàng tận nhà không?",
        "chatbot_answer": "Vâng."
    },
    {
        "customer_question": "Sữa Abbott Grow và Similac khác nhau thế nào?",
        "chatbot_answer": "Similac cho trẻ 0-3 tuổi, Grow cho trẻ lớn hơn."
    },
    {
        "customer_question": "Tôi có thể đổi trả nếu con không uống được không?",
        "chatbot_answer": "Có thể đổi trả trong vòng 7 ngày nếu sản phẩm chưa mở nắp và còn nguyên tem."
    },
    {
        "customer_question": "Sữa Ensure có bị tiểu đường uống được không?",
        "chatbot_answer": "Ensure có dòng Ensure Diabetes Care dành riêng cho người tiểu đường với đường huyết ổn định."
    },
    {
        "customer_question": "Khuyến mãi gì trong tháng này?",
        "chatbot_answer": "Mua 2 tặng 1 cho tất cả dòng sữa Abbott."
    }
])

for i, row in dataset.head(3).iterrows():
    print(f"\n{i+1}. Q: {row['customer_question']}")
    print(f"   A: {row['chatbot_answer']}")

print(f"\n... (total {len(dataset)} samples)")

print("\n" + "=" * 80)
print("🔍 STEP 2: Evaluator Feedback (Auto-generated by LLM)")
print("=" * 80)

# Mock evaluator results (what would be generated)
feedback_data = [
    {
        "quality": "good",
        "explanation": "Câu trả lời chính xác nhưng thiếu chi tiết. Nên bổ sung thông tin về dinh dưỡng và khuyến nghị liều lượng."
    },
    {
        "quality": "good",
        "explanation": "Thông tin giá chính xác nhưng nên thêm link mua hàng và thông tin khuyến mãi."
    },
    {
        "quality": "good",
        "explanation": "Chính xác và chuyên nghiệp. Nên thêm thông tin về các variant của Similac."
    },
    {
        "quality": "good",
        "explanation": "Tư vấn phù hợp nhưng nên giải thích lý do tại sao Ensure Gold tốt cho người cao tuổi."
    },
    {
        "quality": "excellent",
        "explanation": "Câu trả lời chi tiết, chính xác và có tính bán hàng cao. Đáp ứng đúng nhu cầu khách hàng."
    },
    {
        "quality": "poor",
        "explanation": "Câu trả lời quá ngắn gọn, thiếu chuyên nghiệp. Nên bổ sung thông tin về thời gian giao hàng, phí ship, khu vực giao."
    },
    {
        "quality": "good",
        "explanation": "Thông tin cơ bản đúng nhưng thiếu chi tiết về thành phần dinh dưỡng và lợi ích cụ thể của từng loại."
    },
    {
        "quality": "excellent",
        "explanation": "Câu trả lời rất chuyên nghiệp, rõ ràng về chính sách đổi trả. Tạo niềm tin cho khách hàng."
    },
    {
        "quality": "good",
        "explanation": "Thông tin chính xác về sản phẩm Ensure Diabetes Care. Nên thêm thông tin về giá và nơi mua."
    },
    {
        "quality": "poor",
        "explanation": "Thông tin khuyến mãi quá chung chung, không cụ thể. Nên nêu rõ sản phẩm áp dụng, thời gian, điều kiện."
    }
]

# Add feedback to dataset
dataset_with_feedback = dataset.copy()
for col in ["quality", "explanation"]:
    dataset_with_feedback[col] = [f[col] for f in feedback_data]

print("\n📊 Evaluation Results:")
print("-" * 80)
for i, row in dataset_with_feedback.head(5).iterrows():
    print(f"\n{i+1}. Q: {row['customer_question'][:50]}...")
    print(f"   Quality: {row['quality'].upper()}")
    print(f"   Feedback: {row['explanation'][:100]}...")

quality_counts = dataset_with_feedback['quality'].value_counts()
print(f"\n📈 Quality Distribution:")
for quality, count in quality_counts.items():
    percentage = count / len(dataset_with_feedback) * 100
    bar = "█" * int(percentage / 5)
    print(f"   {quality:10s}: {bar} {count} samples ({percentage:.0f}%)")

print("\n" + "=" * 80)
print("🚀 STEP 3: Prompt Optimization Results")
print("=" * 80)

initial_prompt = "Bạn là chatbot bán sữa Abbott. Trả lời: {customer_question}"

optimized_prompt = """Bạn là chuyên viên tư vấn sản phẩm sữa Abbott chuyên nghiệp và thân thiện.

Khi trả lời khách hàng, hãy:
1. Cung cấp thông tin chính xác, chi tiết về sản phẩm Abbott phù hợp
2. Giải thích lý do và lợi ích cụ thể của sản phẩm
3. Bổ sung thông tin về giá, khuyến mãi, chính sách giao hàng/đổi trả khi phù hợp
4. Sử dụng giọng điệu thân thiện, chuyên nghiệp
5. Kết thúc bằng câu hỏi mở để tiếp tục tư vấn

Câu hỏi khách hàng: {customer_question}

Trả lời:"""

print(f"\n🔴 BEFORE (Initial Prompt):")
print(f"   \"{initial_prompt}\"")
print(f"\n   → Too short, lacks professionalism")
print(f"   → No clear guidelines for responses")
print(f"   → Missing sales tactics")

print(f"\n🟢 AFTER (Optimized Prompt):")
print(f"   \"{optimized_prompt[:200]}...\"")
print(f"\n   ✅ Clear professional guidelines")
print(f"   ✅ Structured response format")
print(f"   ✅ Sales-oriented approach")
print(f"   ✅ Customer engagement focus")

print("\n" + "=" * 80)
print("📈 IMPROVEMENT METRICS")
print("=" * 80)

print(f"\n{'Metric':<30} {'Before':<15} {'After':<15} {'Improvement':<15}")
print("-" * 75)
print(f"{'Average Quality':<30} {'6.0/10':<15} {'8.5/10':<15} {'+42%':<15}")
print(f"{'Excellent Responses':<30} {'0%':<15} {'30%':<15} {'+30pp':<15}")
print(f"{'Poor Responses':<30} {'20%':<15} {'5%':<15} {'-75%':<15}")
print(f"{'Customer Satisfaction':<30} {'70%':<15} {'90%':<15} {'+20pp':<15}")

print("\n" + "=" * 80)
print("🧪 STEP 4: Test with Optimized Prompt")
print("=" * 80)

test_cases = [
    "Sữa nào tốt nhất cho bé 2 tuổi biếng ăn?",
    "Có ưu đãi cho khách hàng mua nhiều không?",
    "Sữa Abbott có chứa đường không?"
]

print("\n✅ Test Questions (use optimized prompt for better results):")
for i, q in enumerate(test_cases, 1):
    print(f"\n{i}. {q}")

print("\n" + "=" * 80)
print("✅ DEMO COMPLETE!")
print("=" * 80)

print(f"""
📝 Summary:
   - Dataset: 10 Abbott milk chatbot samples
   - Evaluator: LLM-as-a-Judge with quality assessment
   - Feedback: Auto-generated (8 good, 2 poor)
   - Optimization: 5-step guideline for better responses
   - Result: +42% quality improvement

🚀 Next Steps:
   1. Run with real API: python examples/abbott_chatbot_example.py
   2. Use optimized prompt in production chatbot
   3. Monitor and iterate based on customer feedback

📚 More Info:
   - examples/evaluator_example.py
   - docs/EVALUATOR_PATTERN.md
""")

# Save dataset with feedback
output_file = "/tmp/abbott_chatbot_with_feedback.csv"
dataset_with_feedback.to_csv(output_file, index=False)
print(f"💾 Dataset with feedback saved to: {output_file}")
