"""
Example: Using evaluator pattern via API.

This example shows how to use the /api/v1/optimize endpoint
with evaluators instead of pre-computed feedback.
"""

import requests
import json

# API endpoint
url = "http://localhost:8000/api/v1/optimize"

# Request payload with evaluators
payload = {
    "prompt": "Answer concisely: {question}",
    "dataset": [
        {
            "question": "What is 2+2?",
            "answer": "4",
        },
        {
            "question": "What is the capital of France?",
            "answer": "Paris, the capital city of France",
        },
    ],
    "output_column": "answer",
    "feedback_columns": [],  # Empty - will be generated by evaluators
    "evaluators": [
        {
            "type": "classification",
            "feedback_column": "correctness",
            "model": "gpt-4o",
            "prompt_template": """
                Evaluate this question-answer pair:
                Question: {question}
                Answer: {answer}

                Is the answer correct? Return JSON with:
                "correctness": "correct" or "incorrect"
                "explanation": "brief explanation"
            """,
            "choices": {"correct": 1, "incorrect": 0},
            "include_explanation": True,
        }
    ],
    "model": "gpt-4o",
    "budget": 1.0,
}

# Make request
print("Sending request with evaluator config...")
response = requests.post(url, json=payload)

# Print response
if response.status_code == 200:
    result = response.json()
    print("\nSuccess!")
    print(f"Original prompt: {result['original_prompt']}")
    print(f"Optimized prompt: {result['optimized_prompt']}")
    print(f"Cost: ${result['cost']:.6f}")
    print(f"Budget usage: {result['usage']['budget_usage_percentage']:.2f}%")
else:
    print(f"\nError {response.status_code}:")
    print(response.text)
